name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8, 3.9]

    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run linter
        run: |
          pylint --fail-under 7 app
          exitcode="$?"
          echo "exitcode=$exitcode" >> $GITHUB_OUTPUT
          exit "$exitcode"

      - name: Run unit tests
        run: |
          pytest tests/unit --maxfail=1 --disable-warnings -v
          coverage run -m pytest tests/unit
          coverage report -m

      - name: Run BDD tests (Behave)
        run: behave features/steps/bdd.py

      - name: Run integration tests
        run: |
          pytest --maxfail=1 --disable-warnings -v
          coverage run -m pytest
          coverage report -m
